title: "学习成长笔记"
description: "简单记录学习过程"
baseurl: ""
url: "https://TheSingingSands.github.io"

# 主题设置
theme: minima

# 构建设置
markdown: kramdown
permalink: pretty

# 作者信息
author:
  name: "TheSingingSands"
  email: "TheSingingSands@outlook.com"

# 社交链接
github_username: TheSingingSands

# 插件
plugins:
  - jekyll-feed
  - jekyll-seo-tag